--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PhillipLP255/EasyBroadcast
build-by-default: true
branches:
- master
projects:
  EasyBroadcast:
    path: "EasyBroadcast\"
    icon: "broadcast.png"
...
